"""eqmod new-amendment — pre-registration scaffolding CLI.

Spec: docs/amendments/G20-G23.md §8.

This tool generates the *pre-registration* scaffolding for a new amendment.
It writes:

  - docs/amendments/<ID>.md                  spec stub (must be filled in
                                             before any implementation code)
  - docs/amendments/<ID>-postmortem.md       template (used only on FAILED)
  - tests/test_amendment_<ID>_<slug>.py      test skeleton
  - docs/marker_protocol_<ID>_addendum.md    pre-registered thresholds block
                                             (sits beside docs/marker_protocol.md;
                                             the original marker_protocol.md is
                                             never edited — per the retry rule)
  - README status table row inserted at the right position

It does NOT write implementation code. The pre-registration discipline
documented in docs/amendments/G20-G23.md §2.6 + §9 requires the spec, the
acceptance bar, and the marker addendum to land *before* the test passes
and *before* the substrate code is touched.

Usage:
    python -m tools.new_amendment G21
    python -m tools.new_amendment G21 --slug single-letter-roundtrip --title "Single-letter `a` round-trip"
    python -m tools.new_amendment G21-prime --retry-of G21
    python -m tools.new_amendment --dry-run G99

By default the command refuses to overwrite existing files. Use --force to
overwrite (will not work for a previously-FAILED amendment — those rows are
permanent per spec §2.6).

Exit codes:
    0  scaffolding written successfully
    1  argument or filesystem error
    2  amendment already exists and --force not passed
    3  attempted to overwrite a FAILED amendment (forbidden by retry rule)
"""
from __future__ import annotations

import argparse
import datetime as _dt
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_AMENDMENTS = REPO_ROOT / "docs" / "amendments"
TESTS_DIR = REPO_ROOT / "tests"
README_PATH = REPO_ROOT / "README.md"
MARKER_PROTOCOL_DIR = REPO_ROOT / "docs"

# README status table marker — new rows are inserted just before this line.
# The line itself is the first row after the G17 entry today; the CLI is
# tolerant of the table growing.
STATUS_TABLE_HEADER_RE = re.compile(
    r"^\|\s*Phase\s*\|\s*Mechanism\s*\|\s*Status\s*\|\s*$"
)

# Amendment ID validation: G followed by 1+ digits, optional prime marks
AMENDMENT_ID_RE = re.compile(r"^G\d+(?:[-']?(?:prime|′)){0,5}$")


@dataclass
class AmendmentScaffold:
    """The five paths a single `new-amendment` invocation can write."""
    spec: Path
    postmortem: Path
    test: Path
    marker_addendum: Path
    readme: Path  # patched in place, not replaced


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

SPEC_TEMPLATE = """\
# Amendment {id} — {title}

**Status: PRE-REGISTERED. Not implemented. {gate_status}**
**Frozen: {date}.**
**Spec author: {author}.**
{retry_line}

> This file was generated by `python -m tools.new_amendment {id}`. Fill in
> every `TODO:` block before the first implementation commit. The
> acceptance bar (§3) must be specific and falsifiable. A spec that does
> not pre-register a numeric threshold cannot be merged.

---

## 1. Background

TODO: Why this amendment exists. One paragraph. What gap in the current
substrate does it close? What scientific or engineering question does it
answer? If this is a retry of a FAILED amendment, link to the
post-mortem and state what changed about the design.

## 2. Frozen design decisions

TODO: List the load-bearing choices that, if changed, would force this
amendment to be renumbered. Reference the interview record or design
discussion that produced them.

- TODO

## 3. Acceptance — pre-registered

TODO: The numeric, falsifiable bar. Includes:

- The metric.
- The PASS threshold.
- The FAIL threshold (an explicit lower bound below which the amendment
  is declared FAILED, not just NULL).
- The NULL band (the range between PASS and FAIL where the result is
  reported as inconclusive).
- The negative control's matched-config bar.

If you can't write these numbers down before the run, you don't have an
acceptance bar. You have a vibe.

| # | Metric | PASS | NULL | FAIL |
|---|---|---|---|---|
| {id}.1 | TODO | TODO | TODO | TODO |

## 4. Budget

| | Realistic | Hard ceiling — FAILED if exceeded |
|---|---|---|
| Wall-clock from first commit | TODO weeks | TODO weeks |
| Compute on author's Mac | TODO | TODO |

At the ceiling: a post-mortem is written within 7 days
(`docs/amendments/{id}-postmortem.md`), the verdict is FAILED, and the
amendment row in `README.md` is updated to FAILED. Retry, if any, is a
new amendment number per the retry rule.

## 5. Negative control

TODO: The matched-config control. What does the substrate look like
under identical config but without the instructive content? What is the
control's expected score on the §3 acceptance metric? A pre-registered
control is the discriminating test.

## 6. Out of scope

TODO: List explicitly. The point is to prevent scope creep during the
run. If a finding inside the run requires expanding scope, the right
move is a new amendment, not editing this list.

## 7. Reusable mechanisms surfaced

If this amendment surfaces a generalisable mechanism, it lands in
`docs/patterns/` under a new entry. Link the entry here once written.

- TODO (none yet)

## 8. Source-of-truth links

- Acceptance addendum: `docs/marker_protocol_{id}_addendum.md`
- Test file: `tests/test_amendment_{id}_{slug}.py`
- Post-mortem template (used only if FAILED): `docs/amendments/{id}-postmortem.md`
- Chain context: `docs/amendments/G20-G23.md`
- Marker protocol (main): `docs/marker_protocol.md`
"""

POSTMORTEM_TEMPLATE = """\
# Amendment {id} — post-mortem

**Status: TEMPLATE. Filled in only if {id} reaches its ceiling and is
declared FAILED. While {id} is in flight or PASSed, this file remains a
template.**

The retry rule (docs/amendments/G20-G23.md §2.6) says: a FAILED verdict
is permanent and its acceptance bar is never edited. A retry happens
under a new amendment number with its own pre-registered acceptance.

---

## 1. Verdict

- **Verdict:** FAILED
- **Date sealed:** TODO
- **Wall-clock at ceiling:** TODO
- **Last test run:** TODO (link to CI / local log)

## 2. What was tried

TODO: A narrative of the runs against this amendment's spec. Include:

- The seed sweep that was run.
- The parameters that were varied (within the spec's frozen design).
- The runs that came closest to passing and what their numbers were.
- Why those near-passes were not PASSes.

## 3. Why it failed

TODO: The substantive reason. Not "we didn't have time" — what was the
actual mechanism that prevented PASS? A guess is fine if labelled as a
guess.

## 4. What we learned

TODO: The honest reading. Two or three findings, each one a sentence.
If one of them is reusable beyond this amendment, also add it as an
entry in `docs/patterns/`.

## 5. Retry, if any

If a retry amendment is being designed, link it here:

- **Retry under:** TODO (e.g. `{id}-prime`)
- **What changed:** TODO (architecture / topology / curriculum / etc.)
- **New pre-registered acceptance:** TODO link

If no retry is planned, state that explicitly.

## 6. What does NOT change

The spec at `docs/amendments/{id}.md` is unchanged. Its acceptance bar
is unchanged. Its negative control is unchanged. This file records the
fact of FAIL; it does not retroactively edit the FAILED amendment's bar.
"""

TEST_SKELETON_TEMPLATE = '''\
"""Pre-registered acceptance tests for amendment {id} — {title}.

Spec: docs/amendments/{id}.md
Addendum: docs/marker_protocol_{id}_addendum.md

These tests encode the pre-registered acceptance bar from the spec's §3.
They MUST fail until the amendment is implemented. A test that passes
before the implementation lands is a sign the test is wrong, not that
the substrate already does the thing.

Mark every test in this file with `@pytest.mark.amendment_{id}` so the
amendment can be run in isolation:

    pytest -m amendment_{id}

When the amendment is declared PASSed or FAILED, this file is frozen.
Editing it after the verdict is sealed is a protocol violation.
"""
from __future__ import annotations

import pytest


pytestmark = pytest.mark.amendment_{id_lower}


@pytest.mark.skip(reason="amendment {id} not yet implemented — pre-registered acceptance test")
def test_{id_lower}_main_acceptance():
    """Pre-registered acceptance bar from docs/amendments/{id}.md §3.

    TODO: Replace this skip with the actual test once {id} is implemented.
    The acceptance bar is FROZEN — do not edit thresholds in this test;
    edit only the implementation until the test passes.
    """
    raise NotImplementedError(
        "Pre-registered test for amendment {id}. Spec at docs/amendments/{id}.md."
    )


@pytest.mark.skip(reason="amendment {id} negative control not yet implemented")
def test_{id_lower}_negative_control():
    """Matched-config negative control from docs/amendments/{id}.md §5.

    TODO: Replace this skip with the actual control test once {id} is
    implemented. The control's pass criterion is FROZEN.
    """
    raise NotImplementedError(
        "Pre-registered negative control for amendment {id}. Spec at docs/amendments/{id}.md."
    )
'''

MARKER_ADDENDUM_TEMPLATE = """\
# Marker protocol — addendum for amendment {id}

**Pre-registered: {date}. Frozen.**

This addendum extends `docs/marker_protocol.md` with the pre-registered
acceptance thresholds for amendment {id} ({title}).

Rule (inherited from `docs/marker_protocol.md`): a threshold edited after
a run that "almost passed" is overfitting evidence, and the verdict of
that run is void. New thresholds for retries are added under new
amendment numbers (e.g. `{id}-prime`), not by editing the row below.

---

## Gate before {id} can begin

TODO: List the prerequisite amendments / runs / conditions that must
hold before {id} can start. If no gate, write "None" explicitly — do
not leave this blank.

- TODO

---

## {id} acceptance — pre-registered

| # | Metric | PASS | NULL | FAIL |
|---|---|---|---|---|
| {id}.1 | TODO | TODO | TODO | TODO |

A run is PASS only if **every** row in PASS. Any row in NULL or FAIL
downgrades the whole verdict to that row's category.

## Negative control — pre-registered

TODO: The matched-config control's thresholds, in the same shape as the
acceptance table above.

| # | Metric | Pass criterion (control must not exceed) |
|---|---|---|
| {id}.NC.1 | TODO | TODO |

---

## Budget

- **Wall-clock realistic:** TODO weeks from {id}'s first commit.
- **Wall-clock ceiling:** TODO weeks. At ceiling: FAILED, post-mortem,
  retry under a new amendment number per the retry rule.

---

## Retry record

If {id} is FAILED and a retry is designed, the retry's pre-registered
acceptance lives in its own addendum (`docs/marker_protocol_{id}-prime_addendum.md`).
The row above is **never** edited.
"""

README_STATUS_ROW = (
    "| **{id}** | **{title}** | PRE-REGISTERED — see `docs/amendments/{id}.md` |\n"
)


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------

def _normalise_id(raw: str) -> str:
    """Normalise an amendment id. Accepts G21, g21, G21', G21-prime; emits G21 or G21-prime."""
    s = raw.strip()
    if not s:
        raise ValueError("amendment id is empty")
    s = s[0].upper() + s[1:]  # first letter uppercase
    s = s.replace("′", "-prime")  # unicode prime → ascii
    if not AMENDMENT_ID_RE.match(s):
        raise ValueError(
            f"amendment id {raw!r} does not match expected shape "
            f"(e.g. 'G21', 'G21-prime', 'G21-prime-prime')"
        )
    return s


def _slugify(text: str) -> str:
    """Title → filename slug."""
    s = text.lower().strip()
    s = re.sub(r"[`'\"]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s or "amendment"


def _scaffold_paths(amendment_id: str, slug: str) -> AmendmentScaffold:
    return AmendmentScaffold(
        spec=DOCS_AMENDMENTS / f"{amendment_id}.md",
        postmortem=DOCS_AMENDMENTS / f"{amendment_id}-postmortem.md",
        test=TESTS_DIR / f"test_amendment_{amendment_id}_{slug}.py",
        marker_addendum=MARKER_PROTOCOL_DIR / f"marker_protocol_{amendment_id}_addendum.md",
        readme=README_PATH,
    )


def _is_failed_amendment(spec_path: Path) -> bool:
    """A FAILED amendment's spec contains the marker we render in
    README/post-mortem. Treat any spec whose first non-blank line declares
    FAILED as immutable per the retry rule."""
    if not spec_path.exists():
        return False
    try:
        text = spec_path.read_text(encoding="utf-8")
    except OSError:
        return False
    head = text[:2000]
    # Status line shape: "**Status: FAILED ...**"
    return bool(re.search(r"\*\*Status:\s*FAILED", head, re.IGNORECASE))


def _insert_readme_row(amendment_id: str, title: str, dry_run: bool) -> Optional[str]:
    """Insert a PRE-REGISTERED status row into the README's status table.

    Strategy: find the header `| Phase | Mechanism | Status |`, then insert
    immediately after the *last* contiguous data row of the table. Idempotent:
    if a row for `amendment_id` already exists, do nothing.
    """
    if not README_PATH.exists():
        return "README.md not found — skipping status row insertion."

    text = README_PATH.read_text(encoding="utf-8")
    if f"| **{amendment_id}** |" in text or f"| {amendment_id} |" in text:
        return f"README already mentions {amendment_id} — leaving as is."

    lines = text.splitlines(keepends=True)
    header_idx = None
    for i, line in enumerate(lines):
        if STATUS_TABLE_HEADER_RE.match(line.rstrip("\n")):
            header_idx = i
            break
    if header_idx is None:
        return "README status table header not found — skipping row insertion."

    # Skip the separator row (`|---|---|---|`) and walk down until the table
    # ends (first non-`|` line).
    j = header_idx + 1
    if j < len(lines) and lines[j].lstrip().startswith("|"):
        j += 1  # past the separator
    while j < len(lines) and lines[j].lstrip().startswith("|"):
        j += 1
    insertion = j

    row = README_STATUS_ROW.format(id=amendment_id, title=title)
    if dry_run:
        return f"[dry-run] would insert at README line {insertion + 1}: {row.rstrip()}"

    lines.insert(insertion, row)
    README_PATH.write_text("".join(lines), encoding="utf-8")
    return f"README row inserted at line {insertion + 1}."


def _write_file(path: Path, content: str, force: bool, dry_run: bool) -> str:
    if path.exists() and not force:
        return f"SKIP (exists): {path.relative_to(REPO_ROOT)}"
    if dry_run:
        return f"[dry-run] would write: {path.relative_to(REPO_ROOT)} ({len(content)} bytes)"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return f"WROTE: {path.relative_to(REPO_ROOT)}"


def scaffold(
    amendment_id: str,
    title: str,
    slug: str,
    author: str,
    retry_of: Optional[str],
    gate_status: str,
    force: bool,
    dry_run: bool,
) -> int:
    paths = _scaffold_paths(amendment_id, slug)

    # Retry-rule guard: a previously-FAILED spec cannot be overwritten,
    # even with --force. Force a new id (e.g. G21 → G21-prime).
    if _is_failed_amendment(paths.spec):
        print(
            f"ERROR: {paths.spec.relative_to(REPO_ROOT)} is marked FAILED. "
            f"Per the retry rule, FAILED amendments are permanent. "
            f"Create a new amendment id (e.g. {amendment_id}-prime) instead.",
            file=sys.stderr,
        )
        return 3

    if not force and not dry_run:
        existing = [p for p in (paths.spec, paths.postmortem, paths.test, paths.marker_addendum) if p.exists()]
        if existing:
            print(
                f"ERROR: {len(existing)} target file(s) already exist for {amendment_id}.\n"
                f"  " + "\n  ".join(str(p.relative_to(REPO_ROOT)) for p in existing) + "\n"
                f"Use --force to overwrite (FAILED specs are still protected).",
                file=sys.stderr,
            )
            return 2

    date = _dt.date.today().isoformat()
    retry_line = (
        f"\n**Retry of: {retry_of}** — see `docs/amendments/{retry_of}-postmortem.md` for what motivated this design change.\n"
        if retry_of else ""
    )

    spec_text = SPEC_TEMPLATE.format(
        id=amendment_id, title=title, date=date, author=author,
        gate_status=gate_status, retry_line=retry_line, slug=slug,
    )
    postmortem_text = POSTMORTEM_TEMPLATE.format(id=amendment_id)
    test_text = TEST_SKELETON_TEMPLATE.format(
        id=amendment_id, id_lower=amendment_id.lower().replace("-", "_"),
        title=title,
    )
    marker_text = MARKER_ADDENDUM_TEMPLATE.format(
        id=amendment_id, date=date, title=title,
    )

    results = [
        _write_file(paths.spec, spec_text, force, dry_run),
        _write_file(paths.postmortem, postmortem_text, force, dry_run),
        _write_file(paths.test, test_text, force, dry_run),
        _write_file(paths.marker_addendum, marker_text, force, dry_run),
    ]
    readme_result = _insert_readme_row(amendment_id, title, dry_run)
    if readme_result:
        results.append(readme_result)

    print("\n".join(results))
    print()
    print(f"Amendment {amendment_id} scaffolding {'(dry-run) ready' if dry_run else 'written'}.")
    print("Next steps:")
    print(f"  1. Fill in every TODO in docs/amendments/{amendment_id}.md.")
    print(f"  2. Fill in the marker thresholds in docs/marker_protocol_{amendment_id}_addendum.md.")
    print(f"  3. Convert the skipped tests in tests/test_amendment_{amendment_id}_{slug}.py "
          f"into the actual pre-registered acceptance checks.")
    print(f"  4. ONLY THEN start the implementation.")
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="eqmod-new-amendment",
        description="Scaffold pre-registration documents for a new EQMOD amendment.",
    )
    p.add_argument("amendment_id", help="Amendment id (e.g. G21, G21-prime)")
    p.add_argument("--title", default=None,
                   help="One-line human title (defaults to amendment id)")
    p.add_argument("--slug", default=None,
                   help="Filename slug for the test file (default: derived from title)")
    p.add_argument("--author", default="Michael Kupermann",
                   help="Spec author (default: Michael Kupermann)")
    p.add_argument("--retry-of", default=None,
                   help="If this is a retry of a FAILED amendment, the id of the original (e.g. G21)")
    p.add_argument("--gate-status", default="Gated — see chain spec for prerequisites.",
                   help="One-line gate description shown in the spec header")
    p.add_argument("--force", action="store_true",
                   help="Overwrite existing non-FAILED files (FAILED specs are always protected)")
    p.add_argument("--dry-run", action="store_true",
                   help="Print what would be written, without touching the filesystem")
    return p


def main(argv: Optional[list[str]] = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        amendment_id = _normalise_id(args.amendment_id)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    title = args.title or amendment_id
    slug = args.slug or _slugify(args.title or amendment_id)

    retry_of = None
    if args.retry_of:
        try:
            retry_of = _normalise_id(args.retry_of)
        except ValueError as exc:
            print(f"ERROR (--retry-of): {exc}", file=sys.stderr)
            return 1

    return scaffold(
        amendment_id=amendment_id,
        title=title,
        slug=slug,
        author=args.author,
        retry_of=retry_of,
        gate_status=args.gate_status,
        force=args.force,
        dry_run=args.dry_run,
    )


if __name__ == "__main__":
    sys.exit(main())
