"""JEP-82b - substrate MPC done right: multi-step planning (BFS) THROUGH the substrate world-model."""
import numpy as np
from collections import deque
from world.energy import EnergyNet
def main():
    print("=== JEP-82b: horizon planning THROUGH the substrate world-model (proper MPC) ===", flush=True)
    K=8; rng=np.random.default_rng(82)
    net=EnergyNet(n_per_module=40, n_modules=2, p_in=0.6, p_cross=0.05, beta=1.5, seed=5)
    ring=[rng.choice([-1.0,1.0], net.N) for _ in range(K)]
    for _ in range(250): net.train_epoch(ring, cue_frac=0.5, lr=0.02, relax_steps=20)
    M=net.M; T_next=np.zeros((net.N,net.N)); T_prev=np.zeros((net.N,net.N))
    for i in range(K):
        a=ring[i]; b=ring[(i+1)%K]; T_next+=0.06*np.outer(b,a)*M; T_prev+=0.06*np.outer(a,b)*M
    np.fill_diagonal(T_next,0.0); np.fill_diagonal(T_prev,0.0); Ts={"next":T_next,"prev":T_prev}
    def idx(s): return int(np.argmax([np.mean(np.sign(s)==np.sign(r)) for r in ring]))
    def step(s,act): net.T=Ts[act]; return net.predict_step(s, cleanup_steps=12)
    # PLAN: BFS over states, transitions generated by the SUBSTRATE predictor (the world-model)
    def plan(si,gi):
        seen={si}; q=deque([(si,[])])
        while q:
            ci,path=q.popleft()
            if ci==gi: return path
            if len(path)>=K: continue
            for act in Ts:
                ni=idx(step(ring[ci].copy(),act))
                if ni not in seen: seen.add(ni); q.append((ni,path+[act]))
        return None
    succ=0; pairs=0; plan_ok=0
    for si in range(K):
        for gi in range(K):
            if si==gi: continue
            pairs+=1; path=plan(si,gi)
            if path is None: continue
            plan_ok+=1
            s=ring[si].copy()
            for act in path: s=step(s,act)
            succ+=int(idx(s)==gi and np.mean(np.sign(s)==np.sign(ring[gi]))==1.0)
    reach=succ/pairs
    print(f"   plans found: {plan_ok}/{pairs}; EXACT goal-pattern reach (execute plan on substrate) = {reach:.3f}", flush=True)
    print("\n--- VERDICT ---", flush=True)
    if reach>=0.90:
        print(f"JEP-82b: PASS - planning THROUGH the substrate world-model (BFS over substrate predict_step transitions)", flush=True)
        print(f"reaches the EXACT goal pattern {reach:.2f} of the time, executing the plan on the substrate's own", flush=True)
        print(f"dynamics. The MPC pillar realized on world.energy.EnergyNet - the substrate is the world-model a proper", flush=True)
        print(f"planner rolls forward. Confirms JEP-82's diagnosis: the substrate was fine, greedy control was the flaw.", flush=True)
        print(f"Established (attractor dynamics + planning), named; no novelty.", flush=True)
    else:
        print(f"JEP-82b: PARTIAL/NULL - exact reach {reach:.2f} < 0.90. Recorded honestly.", flush=True)
    print("DONE", flush=True)
if __name__=="__main__": main()
